providers:
  ipstack:
    active: true
    apiKey: '%%ENV:IPSTACK_APIKEY%%'
  ipdata:
    active: true
    apiKey: '%%ENV:IPDATA_APIKEY%%'
  maxmind:
    active: true
    userID: '%%ENV:MAXMIND_USERID%%'
    licenseKey: '%%ENV:MAXMIND_LICENSEKEY%%'
  ipinfo:
    active: true